language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
install:
  - npm install -g codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
